version: '3'
services:
  web:
    image: docker-notesapp
    build: .
    command: "npm start"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
